### ISSUE TITLE
Pass in datomic uri instead of conn-fn?

### ISSUE THREAD

**Issue by dwwoelfel** [sgrove/dato#13]
In the dato server constructor, I think it would be nicer to just pass in the connection uri. Would make the purpose more obvious and make it easier to inspect (answers the question "which database is this dato server connecting to?"). 

Unless there's a use-case where the conn-fn would be something other than (d/connect "some-uri")?

**Comment by sgrove** [comment]
There isn't any, we should just pass in the uri

**Comment by dwwoelfel** [comment]
One sec, I'll submit a PR

**Comment by dwwoelfel** [comment]
Resolved here: https://github.com/sgrove/dato/pull/14
